### ISSUE TITLE
Readme not match with code

### ISSUE THREAD

**Issue by TheRafaelFarias** [Rocketseat/rocketseat-vscode-reactjs-snippets#17]
Hey guys, I'm trying to use other snippets like `rc` and, for some reason, you deleted all the other snippets, just left` styled-react` and `rfc`.

And you didn’t fix the Readme, making anyone who thinks even have other snippets

**Comment by matheuscuba** [comment]
I had the same problem, just downgrade the version of the extension:

![Screen Shot 2020-06-21 at 12 23 07](https://user-images.githubusercontent.com/32616871/85228474-f80acb00-b3b9-11ea-803b-ed68bb60e4fa.png)

I have downgraded to `2.2.0` and everything works just fine.

**Comment by thiagobraga** [comment]
Sorry, amigos. But will this issue remain closed? The guilty commit was "chore: Remove a bunch of unused snippets". "E eu chorei mesmo!"

Not used by whom? By the creator? Because if it is an extension to the community, private tastes should not prevail, I believe. The extension had 20 snippets, and now has only 2. I wasted about 1 hour to understand what happened.

"You can downgrade the extension". Of course I can, but I could also continue working without having this type of intervention, to look for what happened, downgrade the extension, comment on this issue, comment on the Marketplace.

The Marketplace readme also doesn't reflect Github, which is even worse.

**Comment by TheRafaelFarias** [comment]
We have 2 options, fork and maintain or downgrade, I think a fork is better but I don't use more this type of extensions so doesn't make sense I maintain one. But yeah it will still be closed

We don't know why they removed a bunch of snippets but is their project, so we can't do many things
